import { StyleSheet } from "react-native";
import Colors from '../../../shared/themes/colors'

const styles=StyleSheet.create({
    container:{flex:1,backgroundColor:Colors.backgroundColor},
    leftIcon:{marginTop:19, marginLeft:21},
    phoneImage:{width:393, height:321},
    imageContainer:{flexDirection:'row'},
    heartIcon:{position:'absolute',height:18, width:20, right:16,top:56},
    upArrowIcon:{height:24 ,width:24, position:'absolute', right:8, top:33},
    variantSelectText:{marginTop:44, marginLeft:21, fontSize:15},
    lineSeparator:{opacity:0.5,borderWidth:1, marginTop:8},
    variantColorText:{marginTop:6, marginLeft:21, fontSize:15},
    variantStorageText:{marginLeft:21,marginTop:12},
    phoneName:{ fontSize:15, marginLeft:13, marginTop:17 },
    variantColorOptionText:{marginTop:6, fontSize:15},
    variantStorageOptionText:{marginTop:6, marginLeft:170, fontSize:15},
    ratingImage:{width:97,height:16, marginTop:8},
    assuredImage:{position:'absolute',width:99, height:27, right:4,marginTop:4 },
    ratingText:{fontSize:12, marginTop:6,},
    ratingLabelText:{fontSize:12, color:Colors.labelText, marginTop:6,},
    ratingContainer:{flexDirection:'row',  marginLeft:5, gap:2},
    price:{fontSize:20, marginLeft:17, marginTop:21},
    emiPlan:{fontSize:14, marginLeft:13, marginTop:12},
    detailButton:{color:Colors.labelText, marginTop:12, marginLeft:4},
    priceContainer:{flexDirection:'row'},
    priceDecreaseText:{fontSize:15, marginTop:13},
    downArrow:{marginLeft:10, marginTop:13},
    rupeeIcon:{marginTop:13, marginLeft:7},
    notThisText:{fontSize:15, marginTop:10, marginLeft:2},
    priceLineSeparator:{borderWidth:1, width:59, marginLeft:66, bottom:14},
    priceText:{fontSize:16, marginTop:10},
    rupeePriceIcon:{marginTop:13, marginLeft:14},
    payOption:{fontSize:14, marginLeft:13},
    rupeeOptionIcon:{marginLeft:2, marginTop:4},
    payContainer:{flexDirection:'row'},
    payOptionText:{marginTop:1},
    coinImage:{width:14,height:14, marginLeft:2, marginTop:4},
    coinOption:{marginLeft:3, fontSize:13, marginTop:2},
    packageFeeContainer:{flexDirection:'row', marginTop:10},
    plusIcon:{marginLeft:13},
    packingFeeText:{fontSize:11, marginLeft:1, marginTop:1},
    bankOffer:{marginLeft:13, marginTop:9},
    applyNowButton:{color:Colors.labelText, marginLeft:13},
    cartIcon:{marginLeft:54, marginBottom:28},
    bottomButtonContainer:{flexDirection:'row', marginTop:13},
    emiContainer:{borderWidth:1, marginBottom:20,marginLeft:39},
    emiText:{ fontSize:12 , paddingHorizontal:23,paddingTop:3},
    emiTime:{fontSize:10, paddingLeft:23, paddingBottom:3},
    buyButton:{paddingHorizontal:22, backgroundColor:Colors.buyButtonColor,paddingVertical:9, borderRadius:6, marginLeft:14, fontSize:14, fontWeight:500},

})
export default styles;